Implement for-loop in 0.4
fastn-stack/fastn pull request #1107
Opened 2023-07-24 09:25 UTC by harshdoesdev

Implement for-loop in 0.4 as mentioned in https://github.com/orgs/fastn-stack/discussions/1079.

**Syntax:**
```
for: $p in $person
```

2023-07-25 10:59 UTC, Arpita-Jaiswal requested changes

2023-07-25 10:59 UTC, Arpita-Jaiswal commented on ftd/src/ast/component.rs
> +        if loop_header.key.eq("for") {
```suggestion
        if loop_header.key.eq(ftd::ast::utils::FOR) {
```

2023-07-25 10:59 UTC, Arpita-Jaiswal commented on ftd/src/ast/component.rs
> +                );
Copying same logic twice just to get `alias` and `on` differently is not a good idea. Merge the logic and use condition to get `alias` and `on`.

2023-07-25 10:59 UTC, Arpita-Jaiswal commented on ftd/src/ast/component.rs
> +            v.get_key().eq(ftd::ast::utils::LOOP) || v.get_key().eq(ftd::ast::utils::FOR)
```suggestion
            [ftd::ast::utils::LOOP, ftd::ast::utils::FOR].contains(v.get_key())
```

2023-07-25 10:59 UTC, Arpita-Jaiswal commented on ftd/src/ast/component.rs
> +        if loop_header.get_key().eq("for") {
```suggestion
        if loop_header.get_key().eq(ftd::ast::utils::FOR) {
```

2023-07-25 11:02 UTC, Arpita-Jaiswal requested changes

2023-07-25 11:02 UTC, Arpita-Jaiswal commented on ftd/src/ast/component.rs
> +
Again don't copy the logic twice.

2023-07-25 11:09 UTC, amitu commented
WE have to ensure both old and new syntax work. Old syntax should issue a warning.

2023-07-27 11:48 UTC, Heulitig requested changes

2023-07-27 11:48 UTC, Heulitig commented on ftd/src/ast/component.rs
> +            let on = if let Some(on) = on {
Change the below unwrap to this 
```suggestion
            let on = on.ok_or(ftd::ast::Error::Parse {
                message: "Statement \"for\" needs a list to operate on".to_string(),
                doc_id: doc_id.to_string(),
                line_number: loop_header.line_number,
            })?;
```

2023-07-27 11:48 UTC, Heulitig commented on ftd/src/ast/component.rs
> +            let on = if let Some(on) = on {
Similarly update this as well

2023-07-27 11:48 UTC, Heulitig commented on ftd/src/ast/component.rs
> +            key_name,
Rename key_name to loop_counter_alias
```suggestion
            loop_counter_alias,
```

2023-07-27 11:48 UTC, Heulitig commented on ftd/src/interpreter/things/component.rs
> +        key_name: Option<String>,
Similarly refactor this variable name as well
```suggestion
        loop_counter_alias: Option<String>,
```

2023-07-27 11:48 UTC, Heulitig commented on ftd/src/interpreter/utils.rs
> +    if let Some((loop_name, loop_argument, loop_key_name)) = loop_object_name_and_kind {
Same here
```suggestion
    if let Some((loop_name, loop_argument, loop_counter_alias)) = loop_object_name_and_kind {
```

2023-07-27 11:48 UTC, Heulitig commented on ftd/src/ast/component.rs
> +                "Warning: \"$loop$\" is deprecated, use \"for:\" instead".bright_yellow()
Also fix this warning message typo 
```suggestion
                "Warning: \"$loop$\" is deprecated, use \"for\" instead".bright_yellow()
```

2023-07-28 05:08 UTC, Heulitig approved these changes

2023-07-28 11:30 UTC, Arpita-Jaiswal approved these changes

2023-07-28 11:31 UTC, merged